#!/bin/sh

# also update version in doc/index.html : line 12

pkg=Xdialog
ver=$(grep AC_INIT configure.ac  | cut -f 3 -d '[' | cut -f 1 -d ']')

dir=${pkg}-${ver}

sed -i "s|Xdialog v.*<|Xdialog v${ver} documentation<|" \
	docs/index.html

set -x

mkdir -p ../$dir

cp -rf $PWD/* ../$dir

(
	cd ../$dir
	./autogen.sh
	#rm -rf m4
	rm -rf autom4te.cache zrelease
)

cd ..

tar -Jcf ${dir}.tar.xz $dir

### END ###
