#!/bin/sh

. ./0common.sh || exit 1

DIR=$(
$DIALOG --stdout \
        --title "Please choose a directory" \
        --dselect /etc 0 0
)

case $? in
	0)
		echo "\"$DIR\" chosen";;
	1)
		echo "Cancel pressed.";;
	255)
		echo "Box closed.";;
esac
