#!/bin/sh
# --logbox is not compatible with (c)dialog [ncurses]

DIALOG='Xdialog'
if [ -x ./Xdialog ] ; then
    DIALOG='./Xdialog'
elif [ -x ../Xdialog ] ; then
    DIALOG='../Xdialog'
fi

case $1 in
    cli|-cli|--cli)
        DIALOG='dialog'
        echo "this is not compatible with (c)dialog [ncurses]"
        exit 0
        ;;
    *dialog*)
        if [ -x $1 ] ; then
            DIALOG=$1
            shift
        fi
        ;;
esac

echo "$DIALOG"

#================================

LOGFILE=/tmp/logbox.tmp.$$

REVERSE=""
TIMESTAMP=""
CHOICE=`$DIALOG --stdout --title "LOGBOX" \
		--check "I want the messages to appear in reverse order" \
		--no-tags --no-cancel --no-close \
		--radiolist "What type of time stamps do you want in the log box ?" 0 0 0 \
			    "none" "No stamps at all"				"off" \
			    "time" "Time (HH:MM:SS) only"			"off"\
			    "date" "Date and time (DD/MM/YYYY HH:MM:SS)"	"on"`
for i in $CHOICE ; do
	case $i in
		checked)
			REVERSE="--reverse"
			;;
		time)
			TIMESTAMP="--time-stamp"
			;;
		date)
			TIMESTAMP="--date-stamp"
			;;
	esac
done

touch $LOGFILE

$DIALOG --title "LOGBOX" --backtitle "This logbox uses the --keep-colors option" \
	--this-option-does-not-exist-and-will-therefore-be-ignored \
	$TIMESTAMP $REVERSE --keep-colors --smooth --logbox $LOGFILE 0 0 &

echo "Normal text 1." >>$LOGFILE
echo "Normal text 2." >>$LOGFILE
echo "Normal text 3." >>$LOGFILE
sleep 1
echo "Normal text 4." >>$LOGFILE
echo "Normal text 5." >>$LOGFILE
echo "Normal text 6." >>$LOGFILE
sleep 1
echo -e "\\033[1;31mThis is a red foreground text." >>$LOGFILE
echo "Idem." >>$LOGFILE
echo "Idem." >>$LOGFILE
echo -e "\\033[1;38mRevert to normal text." >>$LOGFILE
echo "Normal text 7." >>$LOGFILE
echo "Normal text 8." >>$LOGFILE
echo -e "\\033[1;42mThis is a green background text." >>$LOGFILE
sleep 1
echo "Idem." >>$LOGFILE
echo -e "\\033[1;48mRevert to normal text." >>$LOGFILE
echo "Normal text 9." >>$LOGFILE
sleep 1
echo -e "And now a blue text\\033[1;34;46m on cyan background." >>$LOGFILE
echo "Idem." >>$LOGFILE
echo -e "\\033[1;38;48mRevert to normal text." >>$LOGFILE
echo "Normal text 10." >>$LOGFILE
sleep 2

rm -f $LOGFILE
