#!/bin/sh
# --2inputsbox/--password/-left is not supported by dialog (ncurses)

DIALOG='Xdialog'
if [ -x ./Xdialog ] ; then
    DIALOG='./Xdialog'
elif [ -x ../Xdialog ] ; then
    DIALOG='../Xdialog'
fi

case $1 in
    cli|-cli|--cli)
        DIALOG='dialog'
        echo "this is not compatible with (c)dialog [ncurses]"
        exit 0
        ;;
    *dialog*)
        if [ -x $1 ] ; then
            DIALOG=$1
            shift
        fi
        ;;
esac

echo "$DIALOG"

#================================

LOGIN1=`$DIALOG	--stdout --separator "|" \
		--title "Login" --backtitle "System login" \
		--icon ./dialog-error.png --left --password \
		--2inputsbox "Restricted access, authorized users only !\nPlease login..." 0 0 \
			     "Your login name:" "root" \
			     "Your password:" "" \
		--no-close --no-cancel --msgbox "Thank you !" 0 0`

ret=$?

case $ret in
	0)
		NAME=`echo $LOGIN1 | awk --source 'BEGIN { FS="|" }' --source '{ print $1 }'`
		PASSWD=`echo $LOGIN1 | awk --source 'BEGIN { FS="|" }' --source '{ print $2 }'`
		echo "Name    : $NAME"
		echo "Password: $PASSWD"
		;;
	1)
		echo "Cancel pressed."
		;;
	255)
		echo "Box closed."
		;;
esac
