#!/bin/sh

DIALOG='Xdialog'
if [ -x ./Xdialog ] ; then
    DIALOG='./Xdialog'
elif [ -x ../Xdialog ] ; then
    DIALOG='../Xdialog'
fi

case $1 in
    cli|-cli|--cli)
        DIALOG='dialog'
        shift
        ;;
    *dialog*)
        if [ -x $1 ] ; then
            DIALOG=$1
            shift
        fi
        ;;
esac

echo "$DIALOG"

#================================

$DIALOG --title "TAIL BOX" \
        --backtitle "A simple tail box..." \
        --tailbox /var/log/messages 24 64

case $? in
  0)
    echo "OK.";;
  1)
    echo "Cancel pressed.";;
  255)
    echo "Box closed.";;
esac
