#!/bin/sh
# don't use --menubox, --menu is compatible with the curses dialog
# --check "$CHECKER" is not supported by the ncurses dialog

DIALOG='Xdialog'
if [ -x ./Xdialog ] ; then
    DIALOG='./Xdialog'
elif [ -x ../Xdialog ] ; then
    DIALOG='../Xdialog'
fi

case $1 in
    cli|-cli|--cli)
        DIALOG='dialog'
        shift
        ;;
    *dialog*)
        if [ -x $1 ] ; then
            DIALOG=$1
            shift
        fi
        ;;
esac

echo "$DIALOG"

#================================

TITLE="Screen saver"
PROMPT="Please choose the mode:"
CHECKER="Check to lock the screen"
MENU=/tmp/menu.$$

cat << EOF >$MENU
#!/bin/sh
CHOICE=\$($DIALOG --title "$TITLE" --stdout --no-tags --check "$CHECKER" --default-item "random" --menu "$PROMPT" 0 0 7 \\
EOF
xlock -help | awk --source '{ if (substr($1,1,1) != "-" && $1 != "where" && $1 != "" && $1 != "xlock" && $1 != "usage:") print $1 " " $1 " \\" }' >>$MENU
cat << EOF2 >>$MENU
)
ret=\$?
echo \$CHOICE
exit \$ret
EOF2

chmod +x $MENU
CHOICE=`$MENU`
ret=$?
rm -f $MENU

if (( $ret != 0 )) ; then
	exit 0
fi

for i in $CHOICE ; do
	case $i in
		unchecked)
			NOLOCK="-nolock"
			;;
		checked)
			NOLOCK=""
			;;
		*)
			MODE=$i
			;;
	esac
done
xlock $NOLOCK -mode $MODE
